export const PICAL_ACCOUNT = "PICAL_ACCOUNT";
export const PICAL_ACCOUNT_SUCCESS = "PICAL_ACCOUNT_SUCCESS";
export const PICAL_ACCOUNT_FAIL = "PICAL_ACCOUNT_FAIL";

// SIGN IN
export const ADD_USER = "ADD_USER";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
export const ADD_USER_FAIL = "ADD_USER_FAIL";
